-- AlterTable
ALTER TABLE "Shift" ADD COLUMN     "clockInAccuracyM" DOUBLE PRECISION,
ADD COLUMN     "clockInDistanceM" DOUBLE PRECISION,
ADD COLUMN     "clockInLat" DOUBLE PRECISION,
ADD COLUMN     "clockInLng" DOUBLE PRECISION,
ADD COLUMN     "clockOutAccuracyM" DOUBLE PRECISION,
ADD COLUMN     "clockOutDistanceM" DOUBLE PRECISION,
ADD COLUMN     "clockOutLat" DOUBLE PRECISION,
ADD COLUMN     "clockOutLng" DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Site" ADD COLUMN     "geofenceRadiusM" INTEGER,
ADD COLUMN     "latitude" DOUBLE PRECISION,
ADD COLUMN     "longitude" DOUBLE PRECISION;
